name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
        - "server-api/**"
  pull_request:
    branches: [ main ]
    paths: 
        - "server-api/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
